### ISSUE TITLE
How do I ask a question?

### ISSUE THREAD

**Issue by ericelliott** [learn-javascript-courses/javascript-questions#1]
1. Ask the question as clearly and concisely as you can in the title. Tip: Avoid asking questions related to implementation details. Instead, ask how to solve the real problem you're trying to solve. For instance, instead of asking, "how do I animate this cow walking and chewing grass with jQuery?" try "How do you create smooth sprite animations in the browser?" That way, your question is more useful to other people.

2. Try to find and link to a working example of what you want to do.

3. Describe the things you have already tried. Paste your code examples on a site like [JSBin.com](http://jsbin.com) so that other people can spot bugs and make clear, specific suggestions. If your program is too big for JSBin, try paring it down to the bare minimum you need to reproduce your problem. Often, doing so will help you discover the answer yourself.

Questions formatting can optionally be enhanced using [GitHub flavored markdown](https://help.github.com/articles/github-flavored-markdown).

**Comment by radiovisual** [comment]
Is it alright to ask questions that don't necessarily involve source code, or a solution to a coding problem? Most of the questions I can think to ask are more design/development theory, best practices, and learning more about the advanced nature of javascript. There are few eloquent resources that take you deep into the mechanics and mannerisms of javascript, so I am loaded with questions about advanced javascript usage that I can't easily find anywhere else.

**Comment by ericelliott** [comment]
Of course. Just [open a new issue](https://github.com/learn-javascript-courses/javascript-questions/issues/new) and ask away. =)
