### ISSUE TITLE
Understanding Statelessness: Is functional programming right for front-end developers?

### ISSUE THREAD

**Issue by radiovisual** [learn-javascript-courses/javascript-questions#10]
As the buzz around the interwebs continues to stir up excitement revolving around the timely comeback of the battle-tested development paradigm of functional programming, I keep hearing about the many benefits that accompany the functional programming paradigm, namely: better code reuse, testable code, cleaner code, etc. However, there is also talk about the many benefits of "statelessness", and how statelessness can lead to beautifully-concurrent applications, where your functional program is inherently thread-safe, a big plus. 

So I understand all that from a theoretical point of view. The arguments are sound, but what about from a real-world point of view? Can you explain to me how a front-end web developer can benefit from writing in a "functional" style, where their applications are "stateless"?

The way I think of a single-page web applications (or a massive enterprise application with dozens-to-hundreds of pages) there is a **lot of "state"** that needs to be accounted for. **So how does someone coming from the mindset of a front-end developer start to think about writing code in a "stateless" manner?** Is it possible (and/or practical) to write an entire SPA or enterprise app in a functional and "stateless" style, or it necessary to mix a functional style in with other paradigms to get the job done? 

**Bonus question:** Can you point out some open-source projects that are making brilliant use of the functional paradigms? I would like to study the source code of these projects for educational purposes.

**Comment by ericelliott** [comment]
I mix paradigms on a regular basis.

I don't know of any existing open-source apps that make heavy use of functional programming and statelessness, but I intend to do that with [the Isomorphic Express Boilerplate](https://github.com/ericelliott/isomorphic-express-boilerplate). You might want to bookmark it.

**Comment by ericelliott** [comment]
Check out [The Dao of Immutability](https://medium.com/javascript-scene/the-dao-of-immutability-9f91a70c88cd) for the philosophy behind stateless functions.
