### ISSUE TITLE
deployment in node

### ISSUE THREAD

**Issue by nostalgicdodo** [learn-javascript-courses/javascript-questions#11]
I have a couple of questions on deployment,

1. how to find out how many concurrent requests a node instance can handle? like, for example, the server is a 512MB RAM single-core machine; how do I know if it will be sufficient?
2. how many node processes should be run? child processes or cluster? I've read that you only spawn as many processes as you have cores, but then I've read elsewhere that this is not the case and that you could go higher because node spends most of its time in I/O which is not CPU-bound. Not all of it makes sense.

thank you.

**Comment by ericelliott** [comment]
1) [Run load tests](https://strongloop.com/strongblog/monitoring-stress-testing-nodejs-apps/).
2) I use PM2. Try using a higher or lower number of processes and use the number that performs best in the load tests. 2x CPU might be a good starting point, but your mileage will vary based on the app.

**Comment by nostalgicdodo** [comment]
sorry for the late rep. that's the word I needed to know - "**load testing**"..... now I'm finding relevant info when searching for that term.

thanks a bunch.

**Comment by ericelliott** [comment]
:+1:
