### ISSUE TITLE
Best practices for caching data?

### ISSUE THREAD

**Issue by radiovisual** [learn-javascript-courses/javascript-questions#14]
Hey Eric, 

I have started working on a open-source project called [Birdwatch](https://github.com/radiovisual/birdwatch). The purpose of Birdwatch is to allow developers an easy way to serve cached tweets from one or more twitter feeds (and let them filter the tweets based on hashtags). A caching/serving system is necessary so that Twitter's API request limits are avoided. By default, Birdwatch will request the new data from Twitter every 10 minutes, then cache the data, which in turn gets served on each request by node/express. 

**My question to you is:** what are the best practices for caching data in an application like this? Currently, the data gets saved in an in-memory cache, meaning: the twitter data gets assigned to a variable, and if that variable has data, it serves that to the client, if there is no data in-memory, it looks to the hard-disk for backup, and if not present, it just goes out to get that data from Twitter. Is there anything wrong with that approach? Is there a better way? I have never built a system like this before, so I can only ask if I hope to learn anything. 

Also, [I know I am doing something wrong](https://github.com/radiovisual/birdwatch/blob/master/utils.js#L392) in my [`getCachedTweets()`](https://github.com/radiovisual/birdwatch/blob/master/utils.js#L367) function, where I am setting a `setTimeout` to wait `1200ms` to give my in-memory cache time to be populated before serving the data. It only ever has to do that once when the app first starts up, but even then, I know I am doing something wrong, and there must be a better way. I also had to do things this way to get one of my unit tests to pass, since I didn't know how else to test this particular functionality. **So, knowing there is a better way**, I was hoping to ask you how you would set up a system like this, so that I can clean up some of my mistakes and get this module testable.  

I know that once I get things cleaned up, it will be easier to write tests for this app. [Currently, these three commented out tests fail every time](https://github.com/radiovisual/birdwatch/blob/master/test/test.js#L95), yet my app works perfectly when I run it normally. For example, in production, when I am expecting 4 values to be returned, I get 4 values, but when I write a test to confirm that same behavior, I get 8 or 9 values returned. So it must be something in my app design that is holding me from getting good test coverage, so any guidance you can provide would be appreciated. 

P.S: I just got done reading your article [regarding your favor of Tape over Mocha](https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4), so maybe it's Mocha's shared state that is working against me?

Thanks for your expert guidance!

**Comment by ericelliott** [comment]
Hi,

Your caching strategy sounds fine to display what you have as fast as you can, but it will quickly go stale. I would always serve cached data if you have it, and whether you do or not, always fetch fresh data from Twitter so you can find the newest tweets and add them to your cached collection.

> where I am setting a setTimeout to wait 1200ms to give my in-memory cache time to be populated before serving the data.

Yep. There's definitely a better way. When you do an async read from disk, you'll pass a callback function that gets called when you're done. When you fetch tweets from Twitter, you'll pass a callback function that gets called when there's a response. You can turn both of those into promises, and update your application's in-memory state with the latest data when the callbacks fire.

You can create a model that triggers an event every time the app state gets updated. There is a lot of software that can help you with that. My current favorites are [Redux](https://github.com/rackt/redux) and [Cerebral](https://github.com/christianalfoni/cerebral).

As for Mocha, shared state in general should be avoided. Try to do as much as you can with pure functions and immutable data. See [The Dao of Immutability](https://medium.com/javascript-scene/the-dao-of-immutability-9f91a70c88cd) and [The Two Pillars of JavaScript Part 2](https://medium.com/javascript-scene/the-two-pillars-of-javascript-pt-2-functional-programming-a63aa53a41a4) for more on those topics.

**Comment by radiovisual** [comment]
Thanks @ericelliott ! I appreciate the help. You confirmed some of my suspicions. I will do some refactoring on my module and see if I can get things cleaned up well enough to test, and remove that inexcusable `setTimeout`.

**Comment by ericelliott** [comment]
:+1:
