### ISSUE TITLE
Object creaction new keyword vs Object.create 

### ISSUE THREAD

**Issue by Amerr** [learn-javascript-courses/javascript-questions#15]
I have read multiple sites and articles about Javascript inheritance and cons of using new keyword for creating a object from a Function from your medium sites and links.

I can find the only disadvantage of using new keyword in inheritance is , if we don't call function without new keyword.

var a = Foo(); // this causes mess in global object. if we use ***this*** in the Constructor function

and side effects of using new keyword is ***constructor***  property of the Function's prototype , which is configurable and not reliable.

What are the other disadvantage of using new keyword in inheritance.

I am not able to see the bigger picture of Object creation using ***new*** keyword in inheritance 

Thanks in advance

**Comment by ericelliott** [comment]
My biggest objection to the `new` keyword is that it makes the fairly common switch from a class or constructor to a factory a **breaking change**, and it does so without adding *any value.*

* [How to Fix the ES6 `class` Keyword](https://medium.com/javascript-scene/how-to-fix-the-es6-class-keyword-2d42bb3f4caf)
