### ISSUE TITLE
Enhancing skills in plain JS 

### ISSUE THREAD

**Issue by Amerr** [learn-javascript-courses/javascript-questions#17]
Hi eric , i am working as a frontend developer , Most of my work time is spent on building apps based on frameworks like angular or react.

But i want to improve my skills in understanding core JS and writing in plain vanillar JS . creating a whole application based on plain js. 

I need your suggestion how to improve my skills in this area and what do you practice to improve your knowledge and skills.

**Comment by ericelliott** [comment]
It's not a good idea to build real apps without libraries and frameworks. You'd essentially be reinventing the wheel instead of building a car.

If you're curious about how those frameworks actually work, try implementing similar utilities yourself.
