### ISSUE TITLE
How do you launch concurrent unit tests across your test files?

### ISSUE THREAD

**Issue by radiovisual** [learn-javascript-courses/javascript-questions#21]
In your article [Why I use Tape Instead of Mocha & So Should You](https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4#.iookac8fo) you have the following section:

> #### Parallel Testing
> 
>  Think you’ll miss automagic test parallelization? I keep tests for different modules in different files.  It takes about five minutes to write a little wrapper that will fire up workers across all your machine cores and zip through them in parallel.

Can you show me what it looks like to _"write a little wrapper that will fire up workers across all your machine cores and zip through them in parallel"_ using the Tape (or Blue Tape) syntax?

Thanks!

**Comment by ericelliott** [comment]
Keep in mind, with tape, you can simply point node at any file that's using tape, and it will do the right thing... so, create a list of the test files you want to run, and then fork them into [child processes](https://nodejs.org/api/child_process.html).

**Comment by radiovisual** [comment]
So if I have a directory structure like this:

<pre>
index.js
test.js
tests/
    test01.js
    test01.js
</pre>

Then my `test.js` file might look something like this:

```js
const fork = require('child_process').fork;

fork('node tests/test01.js', (error, stdout, stderr) => {
 // ...test01.js test here
});

fork('node tests/test02.js', (error, stdout, stderr) => {
 // ...test02.js test here
});
```

Is that the basic idea? I have one file that launches my separate test files into their own child processes?

**Comment by ericelliott** [comment]
Yeah, pretty much. If any child process reports an error, **the main process should also exit with an error** code. You may also want to do something sensible with the stdout and stderr streams, and not just pipe them directly to the parent's streams in realtime.

**Comment by radiovisual** [comment]
Awesome. As always, thanks for your guidance. 👍
