### ISSUE TITLE
Array methods() and objects

### ISSUE THREAD

**Issue by JaylanSnelson** [learn-javascript-courses/javascript-questions#23]
I am working through free code camp and I am on the Object Oriented and Functional Programming section. Does anyone know a good video to explain objects and array methods in a simple way for beginners?

**Comment by Darlene1** [comment]
Check out this link:  https://medium.com/@ruthmpardee/saving-and-changing-arrays-and-objects-for-javascript-beginners-dc891c9d712e?source=linkShare-f45658a1929d-1482958565

**Comment by Darlene1** [comment]
I'm learning on Free Code Camp too.  JavaScript is hard!

**Comment by Darlene1** [comment]
If I find a video I'll let you know.

**Comment by JaylanSnelson** [comment]
The article did help and I will be looking forward to the video if you find one!
