### ISSUE TITLE
What is so scary about the keyword `this`? What should developers be aware of?

### ISSUE THREAD

**Issue by radiovisual** [learn-javascript-courses/javascript-questions#3]
So I recently watched Douglas Crockford's "The Better Parts", and I was surprised to learn that [he stopped using `Object.create()`, because he stopped using the keyword `this`](https://www.youtube.com/watch?v=bo36MrBfTk4#t=1155)...

Can you explain why the keyword `this` is something that a Javascript guru would choose to stop using in general? What are the benefits to avoiding `this` and how can we learn to use it safely, if we even need it at all? Should we all be avoiding `this`? What am I missing?

**Comment by ericelliott** [comment]
The short answer is that `this` implies some sort of stateful object. There's a growing trend in the JavaScript community to favor a (mostly) stateless approach to programming called functional programming. See [The Two Pillars of JavaScript Part 2: Functional Programming](https://medium.com/javascript-scene/the-two-pillars-of-javascript-pt-2-functional-programming-a63aa53a41a4).

**Comment by radiovisual** [comment]
Awesome, as always, I appreciate the thorough response. Can you clarify what an FRP-style application is, and what it means to be "pure" vs. "impure". Thanks!

**Comment by ericelliott** [comment]
Those should both be made clear when you read [The Two Pillars of JavaScript Part 2](https://medium.com/javascript-scene/the-two-pillars-of-javascript-pt-2-functional-programming-a63aa53a41a4).

**Comment by ericelliott** [comment]
:+1:

**Comment by radiovisual** [comment]
Awesome. Thanks!
