### ISSUE TITLE
What every beginning open source developer should know

### ISSUE THREAD

**Issue by radiovisual** [learn-javascript-courses/javascript-questions#4]
I have been itching to get into open source development in javascript, because I have ideas for libraries and utilities, as well as some custom implementations that I have built for past projects that I wouldn't mind sharing (and building) with the community, but I don't know much about the process, and it can be a bit intimidating at first, since you get the feeling that open source is reserved for the elite, and there is no room for newbies.

So I would like to ask a few questions regarding open source development:

**1) At what point is a developer ready to start writing open source projects that don't suck?** I have never been able to find a book, or online resource that helps introduce a developer to the world of open-source, or help a beginner learn from the mistakes of others, so I assume the best way to learn, is to learn by doing (which goes without saying), but with all that said, it would still be nice to hear some advice, gotchas, pitfalls and war stories from a seasoned professional. 

**2) Besides the knowledge of a VCS like git, what should any javascript developer know before they start to contribute to projects, or start writing their own?** Is it imperative to be a javascript master before you even think about getting involved, or is it encouraged to get involved and learn from the community? 

**3) What is the secret to writing extendable, maintainable code?** Are there design principles or practices that are favored in open source? Or is just as simple as "there is no secret", every project is different. 

**4) How do open source developers keep each other in check?** If you have 10 contributors that don't really know what they are doing, you just end up with a messy pile of code...or is that all part of the process, and bad libraries are more common than good ones? 

**5) Is it common for a beginner to contribute, or is open-source saved for the elite?**

**6) What are some of the biggest lessons you have learned in your experience writing open source libraries?**

**7) Do you know of any great resources to help prepare someone for the world of open source?**

Thanks!

**Comment by radiovisual** [comment]
Awesome. This was very helpful. Thanks for all the insight and encouragement!

**Comment by ericelliott** [comment]
:+1:

**Comment by rampavan90** [comment]
Great answer.It is extremely helpful for newbies like me.Thank you so much.I appreciate your work erice elliot.
