### ISSUE TITLE
What's the difference between chainable functions and promises?

### ISSUE THREAD

**Issue by radiovisual** [learn-javascript-courses/javascript-questions#5]
I am new enough to promises that I have seen them in source code, but I have never used them in my own code. What I have used, however, are chainable functions in jQuery. At first glance, these chainable functions and promises tend to "read" the same, like this: *"do something, then do something else, then when you are done, do this..."* but even though they tend to "read" exactly the same, they don't seem to get treated the same in discussion. Consider this line of jQuery:

    myElement.css("color","red").slideUp(100).slideDown(100);

Then examine this line of similar code, using the same format as Promises:

    myElement.assignColor("red").then(slideUp(100)).then(slideDown(100));

These two lines of code would essentially do the same thing, yet I would never hear anyone refer to the jQuery chaining as a "promise"...even though the idea is the same: *"wait for a function to return, then do something, then do something else..."*, so what key principle am I missing here?

I am about to put my reading glasses on and start to study the Promise architecture in-depth so I can understand the underlying language features that drive the mechanics of a promise, but before I did, I was hoping to hear a little discourse on the nature of chainable functions and how they relate to Promises. 

**So are chainable functions and Promises the same thing under the hood?**

**Comment by radiovisual** [comment]
Ah. You're right. **Now I see it clear as day!** I should have done a little more research before asking, so feel free to delete this question, or move it to the "Stupid Questions" category. haha. :beer: 

Clearly, the Promises setup and the chainable functions setup are very different, and used for two very different purposes. At first glance, they seemed to have a similar purpose. 

Thanks for clearing that up!

**Comment by ericelliott** [comment]
:+1:
