### ISSUE TITLE
Is settimeout a function considered as recursive call?

### ISSUE THREAD

**Issue by gdbtek** [learn-javascript-courses/javascript-questions#6]
Hi @ericelliott ,

Recently I have a code review and I spot a sample code using setTimeout like this:

```
module.exports.test = function (params, checkInterval, callback) {
  var route53 = new AWS.Route53(credentials);
  route53.getChange(params, function (err, data) {
    if (err) {
      callback(err);
    } else {
      setTimeout(exports.test, checkInterval, params, checkInterval, callback);
    }
  });
};

test(someParams, 1000, aCallBack);
```

* I'm wondering if this is considered as **recursive call**? As I tested it, I did not see stack growing but I'm not sure if my test is sufficient enough to confirm my answer.

* I don't use setTimeout that much so I was thinking to use [async control flow](https://github.com/caolan/async#control-flow) such as [doWhilst](https://github.com/caolan/async#doWhilst) instead of setTimeout because I prefer to avoid having to pass in **checkInterval** in paramters. Do you have any feedback between async vs setTimeout or maybe you have a better idea? What is the best practice?

Thanks @ericelliott

**Comment by gdbtek** [comment]
Thanks so much for your feedbacks @ericelliott ! :+1:

**Comment by ericelliott** [comment]
Any time. =)
